# Version of runt to be used with this configuration.
ver = "0.2.7"

# Configuration for each test suite. File paths are relative to the folder
# containing runt.toml.
[[tests]]
name = "Cat tests"
paths = [ "cat-test/*" ]
cmd = "sleep $(echo {} | cut -d'/' -f2); cat {}"
expect_dir = "cat-out/"

[[tests]]
name = "Ls test"
paths = [ "cat-test/*" ]
cmd = "sleep $(echo {} | cut -d'/' -f2); ls {}"
expect_dir = "ls-out/"